### ISSUE TITLE
config error in server log

### ISSUE THREAD

**Issue by wackoamd1** [b3spectacled/custom-spawns#4]
<html>
<body>

Failed to load config 'class com.bespectacled.customspawn.config.CustomSpawnConfig', using default!
--
me.shedaniel.autoconfig.serializer.ConfigSerializer$SerializationException: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated array at line 67 column 4 path $.mobSpawnRemovals[2]
at me.shedaniel.autoconfig.serializer.GsonConfigSerializer.deserialize(GsonConfigSerializer.java:83) ~[cloth-config-6.1.48-fabric.jar:?]
at me.shedaniel.autoconfig.ConfigManager.load(ConfigManager.java:92) ~[cloth-config-6.1.48-fabric.jar:?]
at me.shedaniel.autoconfig.ConfigManager.<init>(ConfigManager.java:53) ~[cloth-config-6.1.48-fabric.jar:?]
at me.shedaniel.autoconfig.AutoConfig.register(AutoConfig.java:66) ~[cloth-config-6.1.48-fabric.jar:?]
at com.bespectacled.customspawn.CustomSpawn.<clinit>(CustomSpawn.java:18) ~[custom-spawns-0.6+1.18.jar:?]
at net.minecraft.class_1311.<clinit>(class_1311.java:24) ~[server-intermediary.jar:?]
at net.minecraft.class_1299.<clinit>(class_1299.java:161) ~[server-intermediary.jar:?]
at net.minecraft.class_3103.<clinit>(class_3103.java:28) ~[server-intermediary.jar:?]
at net.minecraft.class_3031.<clinit>(class_3031.java:81) ~[server-intermediary.jar:?]
at net.minecraft.class_6800.<clinit>(class_6800.java:19) ~[server-intermediary.jar:?]
at net.minecraft.class_6803.method_39702(class_6803.java:20) ~[server-intermediary.jar:?]
at net.minecraft.class_5458.method_30566(class_5458.java:78) ~[server-intermediary.jar:?]
at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) [?:?]
at net.minecraft.class_5458.<clinit>(class_5458.java:77) [server-intermediary.jar:?]
at net.minecraft.class_2378.<clinit>(class_2378.java:269) [server-intermediary.jar:?]
at net.minecraft.class_2966.method_12851(class_2966.java:49) [server-intermediary.jar:?]
at net.minecraft.server.Main.main(Main.java:101) [server-intermediary.jar:?]
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608) [fabric-loader-0.12.12.jar:?]
at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.12.12.jar:?]
at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.12.12.jar:?]
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:66) [fabric-loader-0.12.12.jar:?]
Caused by: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated array at line 67 column 4 path $.mobSpawnRemovals[2]
at com.google.gson.Gson.fromJson(Gson.java:947) ~[gson-2.8.8.jar:?]
at com.google.gson.Gson.fromJson(Gson.java:870) ~[gson-2.8.8.jar:?]
at me.shedaniel.autoconfig.serializer.GsonConfigSerializer.deserialize(GsonConfigSerializer.java:79) ~[cloth-config-6.1.48-fabric.jar:?]
... 28 more
Caused by: com.google.gson.stream.MalformedJsonException: Unterminated array at line 67 column 4 path $.mobSpawnRemovals[2]
at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1562) ~[gson-2.8.8.jar:?]
at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:475) ~[gson-2.8.8.jar:?]
at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:413) ~[gson-2.8.8.jar:?]
at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:81) ~[gson-2.8.8.jar:?]
at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61) ~[gson-2.8.8.jar:?]
at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131) ~[gson-2.8.8.jar:?]
at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222) ~[gson-2.8.8.jar:?]
at com.google.gson.Gson.fromJson(Gson.java:932) ~[gson-2.8.8.jar:?]
at com.google.gson.Gson.fromJson(Gson.java:870) ~[gson-2.8.8.jar:?]
at me.shedaniel.autoconfig.serializer.GsonConfigSerializer.deserialize(GsonConfigSerializer.java:79) ~[cloth-config-6.1.48-fabric.jar:?]
... 28 more

</body>
</html>
any idea why i get this error , it just wont load the config . 
i know i doesnt load the config because i changed the spawns and they dont work
and since it doesnt load the config , for now it is basicly useless

**Comment by b3spectacled** [comment]
Please share the config modifications.
