### ISSUE TITLE
Mod 'Fabric Rendering Fluids (v1)' (fabric-rendering-fluids-v1) 0.2.1+6d0fac4218 recommends any version of fabric-textures-v0, which is disabled for this environment (client/server only)! 	 - You should install any version of fabric-textures-v0 for the optimal experience.

### ISSUE THREAD

**Issue by cutemeilu** [b3spectacled/custom-spawns#5]
I only install this mod and it crash 
[20:33:18] [main/INFO]: Loading Minecraft 1.17.1 with Fabric Loader 0.12.12
[20:33:18] [main/WARN]: Warnings were found!
 - Mod 'Fabric Rendering Fluids (v1)' (fabric-rendering-fluids-v1) 0.2.1+6d0fac4218 recommends any version of fabric-textures-v0, which is disabled for this environment (client/server only)!
	 - You should install any version of fabric-textures-v0 for the optimal experience.
[20:33:18] [main/INFO]: Loading 41 mods:
	- cloth-basic-math 0.6.0 via cloth-config2
	- cloth-config2 5.2.47
	- customspawns 0.6+1.17.1
	- fabric 0.42.1+1.17
	- fabric-api-base 0.4.0+5847535018 via fabric
	- fabric-api-lookup-api-v1 1.3.1+5847535018 via fabric
	- fabric-biome-api-v1 3.2.2+5847535018 via fabric
	- fabric-command-api-v1 1.1.4+5847535018 via fabric
	- fabric-commands-v0 0.2.3+5847535018 via fabric
	- fabric-containers-v0 0.1.13+5847535018 via fabric
	- fabric-content-registries-v0 0.3.1+5847535018 via fabric
	- fabric-crash-report-info-v1 0.1.6+5847535018 via fabric
	- fabric-dimensions-v1 2.0.13+5847535018 via fabric
	- fabric-entity-events-v1 1.3.1+5847535018 via fabric
	- fabric-events-interaction-v0 0.4.11+5847535018 via fabric
	- fabric-events-lifecycle-v0 0.2.2+5847535018 via fabric
	- fabric-game-rule-api-v1 1.0.8+5847535018 via fabric
	- fabric-item-api-v1 1.2.5+5847535018 via fabric
	- fabric-item-groups-v0 0.3.1+5847535018 via fabric
	- fabric-lifecycle-events-v1 1.4.5+5847535018 via fabric
	- fabric-loot-tables-v1 1.0.5+5847535018 via fabric
	- fabric-mining-level-api-v1 1.0.2+6d0fac4218 via fabric
	- fabric-mining-levels-v0 0.1.5+6d0fac4218 via fabric
	- fabric-networking-api-v1 1.0.14+5847535018 via fabric
	- fabric-networking-blockentity-v0 0.2.12+5847535018 via fabric
	- fabric-networking-v0 0.3.3+5847535018 via fabric
	- fabric-object-builder-api-v1 1.10.11+6d0fac4218 via fabric
	- fabric-object-builders-v0 0.7.5+6d0fac4218 via fabric
	- fabric-particles-v1 0.2.5+5847535018 via fabric
	- fabric-registry-sync-v0 0.7.13+5847535018 via fabric
	- fabric-rendering-data-attachment-v1 0.1.6+5847535018 via fabric
	- fabric-rendering-fluids-v1 0.2.1+6d0fac4218 via fabric
	- fabric-resource-loader-v0 0.4.9+5847535018 via fabric
	- fabric-screen-handler-api-v1 1.1.9+5847535018 via fabric
	- fabric-structure-api-v1 1.1.14+5847535018 via fabric
	- fabric-tag-extensions-v0 1.2.2+5847535018 via fabric
	- fabric-tool-attribute-api-v1 1.3.1+eb76084f18 via fabric
	- fabric-transfer-api-v1 1.5.1+6d0fac4218 via fabric
	- fabricloader 0.12.12
	- java 17
	- minecraft 1.17.1
[20:33:18] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.4 Source=file:/C:/Users/User/Desktop/Fabricmods/libraries/net/fabricmc/sponge-mixin/0.10.7+mixin.0.8.4/sponge-mixin-0.10.7+mixin.0.8.4.jar Service=Knot/Fabric Env=SERVER
[20:33:19] [main/INFO]: Compatibility level set to JAVA_16
[20:33:28] [main/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.ExceptionInInitializerError
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:610) ~[fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.12.12.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:66) [fabric-loader-0.12.12.jar:?]
Caused by: java.lang.ExceptionInInitializerError
	at net.minecraft.class_1311.<clinit>(class_1311.java:22) ~[server-intermediary.jar:?]
	at net.minecraft.class_1299.<clinit>(class_1299.java:161) ~[server-intermediary.jar:?]
	at net.minecraft.class_3103.<clinit>(class_3103.java:28) ~[server-intermediary.jar:?]
	at net.minecraft.class_3031.<clinit>(class_3031.java:80) ~[server-intermediary.jar:?]
	at net.minecraft.class_5464.<clinit>(class_5464.java:184) ~[server-intermediary.jar:?]
	at net.minecraft.class_5458.method_30571(class_5458.java:46) ~[server-intermediary.jar:?]
	at net.minecraft.class_5458.method_30566(class_5458.java:75) ~[server-intermediary.jar:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
	at net.minecraft.class_5458.<clinit>(class_5458.java:74) ~[server-intermediary.jar:?]
	at net.minecraft.class_2378.<clinit>(class_2378.java:266) ~[server-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:44) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:92) ~[server-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608) ~[fabric-loader-0.12.12.jar:?]
	... 7 more
Caused by: java.lang.NullPointerException: Cannot invoke "me.shedaniel.autoconfig.ConfigData.validatePostLoad()" because "this.config" is null
	at me.shedaniel.autoconfig.ConfigManager.load(ConfigManager.java:106) ~[cloth-config-5.2.47-fabric.jar:?]
	at me.shedaniel.autoconfig.ConfigManager.<init>(ConfigManager.java:53) ~[cloth-config-5.2.47-fabric.jar:?]
	at me.shedaniel.autoconfig.AutoConfig.register(AutoConfig.java:66) ~[cloth-config-5.2.47-fabric.jar:?]
	at com.bespectacled.customspawn.CustomSpawn.<clinit>(CustomSpawn.java:18) ~[custom-spawns-0.6+1.17.1.jar:?]
	at net.minecraft.class_1311.<clinit>(class_1311.java:22) ~[server-intermediary.jar:?]
	at net.minecraft.class_1299.<clinit>(class_1299.java:161) ~[server-intermediary.jar:?]
	at net.minecraft.class_3103.<clinit>(class_3103.java:28) ~[server-intermediary.jar:?]
	at net.minecraft.class_3031.<clinit>(class_3031.java:80) ~[server-intermediary.jar:?]
	at net.minecraft.class_5464.<clinit>(class_5464.java:184) ~[server-intermediary.jar:?]
	at net.minecraft.class_5458.method_30571(class_5458.java:46) ~[server-intermediary.jar:?]
	at net.minecraft.class_5458.method_30566(class_5458.java:75) ~[server-intermediary.jar:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
	at net.minecraft.class_5458.<clinit>(class_5458.java:74) ~[server-intermediary.jar:?]
	at net.minecraft.class_2378.<clinit>(class_2378.java:266) ~[server-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:44) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:92) ~[server-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608) ~[fabric-loader-0.12.12.jar:?]
	... 7 more
![unknown222](https://user-images.githubusercontent.com/98354546/151548117-60f4a3e8-50d9-4011-a991-bca871608168.png)

**Comment by koelle25** [comment]
```
Caused by: java.lang.NullPointerException: Cannot invoke "me.shedaniel.autoconfig.ConfigData.validatePostLoad()" because "this.config" is null
at me.shedaniel.autoconfig.ConfigManager.load(ConfigManager.java:106) ~[cloth-config-5.2.47-fabric.jar:?]
at me.shedaniel.autoconfig.ConfigManager.(ConfigManager.java:53) ~[cloth-config-5.2.47-fabric.jar:?]
at me.shedaniel.autoconfig.AutoConfig.register(AutoConfig.java:66) ~[cloth-config-5.2.47-fabric.jar:?]
at com.bespectacled.customspawn.CustomSpawn.(CustomSpawn.java:18) ~[custom-spawns-0.6+1.17.1.jar:?]
```

This seems to be the actual error. Try deleting any config file regarding custom-spawns you have if any.
